export const summaryCards = [
  { title: 'Total Balance', value: '24,500 USDC', change: '+12.5%', trend: 'up', icon: 'wallet' },
  { title: 'Active Projects', value: '8', change: '+2 new', trend: 'up', icon: 'briefcase' },
  { title: 'Total Clients', value: '24', change: '+4 this month', trend: 'up', icon: 'users' },
  { title: 'Monthly Revenue', value: '45,280 USDC', change: '+18.2%', trend: 'up', icon: 'chart' },
]

export const overviewData = {
  projects: [
    { name: 'DeFi Platform UI', client: 'CryptoVentures LLC', amount: '4,800 USDC', deadline: 'Dec 15', status: 'active' },
    { name: 'NFT Marketplace', client: 'Digital Arts Co', amount: '7,200 USDC', deadline: 'Dec 20', status: 'active' },
    { name: 'Smart Contract Audit', client: 'BlockChain Inc', amount: '82,000 USDC', deadline: 'Dec 18', status: 'pending' },
    { name: 'Web3 Integration', client: 'Tech Innovators', amount: '2,850 USDC', deadline: 'Nov 30', status: 'completed' },
  ],
  transactions: [
    { title: 'Payment from CryptoVentures', date: 'Dec 1, 2025', amount: '+4,800 USDC', status: 'completed', type: 'in' },
    { title: 'Milestone payment - NFT Project', date: 'Nov 28, 2025', amount: '+3,650 USDC', status: 'completed', type: 'in' },
    { title: 'Platform fees', date: 'Nov 27, 2025', amount: '-95 USDC', status: 'completed', type: 'out' },
    { title: 'Client deposit', date: 'Nov 25, 2025', amount: '+55,000 USDC', status: 'pending', type: 'in' },
  ],
}

export const contractData = [
  { name: 'DeFi Platform Development', client: 'CryptoVentures LLC', amount: '9,600 USDC', period: 'Dec 1 - Jan 31', status: 'active' },
  { name: 'Smart Contract Audit', client: 'BlockChain Inc', amount: '240,000 USDC', period: 'Dec 15 - Dec 30', status: 'signed' },
  { name: 'NFT Marketplace Contract', client: 'Digital Arts Co', amount: '8,000 USDC', period: 'Dec 10 - Feb 10', status: 'pending' },
  { name: 'Layer2 UI/UX Retainer', client: 'Layer2 Labs', amount: '12,000 USDC', period: 'Nov 1 - Dec 15', status: 'litige' },
]

export const jobData = [
  {
    id: 'job-1',
    title: 'Senior Web3 Developer',
    company: 'DeFi Protocol',
    location: 'Remote',
    posted: '2 days ago',
    tags: ['Solidity', 'React', 'Web3.js'],
    budget: '8,000-12,000 USDC/month',
    type: 'full-time',
    cta: 'Apply Now',
    status: 'En Attente',
    expected: 'Integration complete front + smart contracts pour dashboard DeFi, tests unitaires inclus.',
    delivered: 'Phase de cadrage terminee, POC front livre.',
    applied: false,
    applicants: [
      {
        id: 'app-1',
        name: 'Alex Martin',
        title: 'Fullstack Web3 Engineer',
        rate: '110 USDC/hr',
        availability: '20 hrs/week',
        skills: ['Solidity', 'TypeScript', 'Ethers.js'],
        note: 'A realise un bridge L2 similaire, dispo immediate.',
      },
      {
        id: 'app-1b',
        name: 'Clara Duval',
        title: 'Frontend + Web3',
        rate: '95 USDC/hr',
        availability: '25 hrs/week',
        skills: ['React', 'Next.js', 'Web3.js'],
        note: 'A livre plusieurs dashboards DeFi responsive.',
      },
      {
        id: 'app-1c',
        name: 'Samir Patel',
        title: 'Smart Contract Dev',
        rate: '120 USDC/hr',
        availability: '15 hrs/week',
        skills: ['Solidity', 'Hardhat', 'Ethers.js'],
        note: 'Focus sur securite et gas optimisation.',
      },
      {
        id: 'app-1d',
        name: 'Lina Ortega',
        title: 'Product Engineer',
        rate: '105 USDC/hr',
        availability: '18 hrs/week',
        skills: ['TypeScript', 'UI/UX', 'Web3'],
        note: 'Peut prendre la partie produit + livrables UI.',
      },
    ],
  },
  {
    id: 'job-2',
    title: 'Smart Contract Auditor',
    company: 'Security Firm',
    location: 'USA/EU',
    posted: '1 week ago',
    tags: ['Solidity', 'Security', 'Hardhat'],
    budget: '15,000 USDC',
    type: 'contract',
    cta: 'Apply Now',
    status: 'En Cours',
    expected: 'Audit complet avec rapport, couverture de tests et recommandations de mitigation.',
    delivered: 'Revue partielle des contrats, rapport intermediaire fourni.',
    applied: false,
    applicants: [
      {
        id: 'app-2',
        name: 'Mina Chen',
        title: 'Smart Contract Auditor',
        rate: '150 USDC/hr',
        availability: '15 hrs/week',
        skills: ['Hardhat', 'Slither', 'Foundry'],
        note: 'Audits DeFi $80M TVL, livre rapports detailles.',
        profile: {
          name: 'Mina Chen',
          title: 'Smart Contract Auditor',
          location: 'Remote - EU/US friendly',
          rate: '150 USDC/hr',
          availability: '10-15 hrs/week',
          bio: 'Audits de protocols DeFi et bridges, rapports détaillés avec mitigations et tests.',
          skills: ['Hardhat', 'Slither', 'Foundry', 'Echidna', 'Manual review'],
          highlights: [
            'Audited $250M TVL protocols (no criticals post-release)',
            'Coverage out-of-the-box avec tests fuzz + invariants',
            'Rapports courts, orientés mitigation',
          ],
          portfolio: [
            { label: 'Bridge Audit', link: '#', tech: 'Hardhat, Slither' },
            { label: 'AMM Audit', link: '#', tech: 'Foundry, Echidna' },
            { label: 'DAO Treasury', link: '#', tech: 'Manual review, zk-SNARK flows' },
          ],
        },
      },
      {
        id: 'app-3',
        name: 'Leo Martins',
        title: 'Solidity Auditor',
        rate: '140 USDC/hr',
        availability: '10 hrs/week',
        skills: ['Foundry', 'Echidna', 'MythX'],
        note: 'Rapports concis, focus sur vulnérabilites logiques.',
      },
      {
        id: 'app-4',
        name: 'Priya Singh',
        title: 'Security Researcher',
        rate: '160 USDC/hr',
        availability: '12 hrs/week',
        skills: ['Slither', 'Spearbit-style reviews', 'Manual tests'],
        note: 'Audit AMM/bridge, propose un plan de mitigation.',
      },
      {
        id: 'app-4b',
        name: 'Jonas Weber',
        title: 'Smart Contract Security',
        rate: '145 USDC/hr',
        availability: '10 hrs/week',
        skills: ['Foundry', 'Formal verification', 'Manual review'],
        note: 'Experience sur options/derivatives protocoles.',
      },
    ],
  },
  {
    id: 'job-3',
    title: 'Blockchain Consultant',
    company: 'StartupDAO',
    location: 'Remote',
    posted: '3 days ago',
    tags: ['DeFi', 'Tokenomics', 'Strategy'],
    budget: '5,000 USDC/month',
    type: 'part-time',
    cta: 'Apply Now',
    status: 'Valide',
    expected: 'Roadmap tokenomics, strategie de gouvernance, ateliers produit.',
    delivered: 'Roadmap et livrables valides, ateliers completes.',
    applied: false,
    applicants: [
      {
        id: 'app-5',
        name: 'Sara Lopez',
        title: 'DeFi Strategist',
        rate: '100 USDC/hr',
        availability: '8 hrs/week',
        skills: ['Tokenomics', 'Governance', 'Workshops'],
        note: 'A piloté 2 DAO sur leur phase de lancement.',
      },
    ],
  },
  {
    id: 'job-4',
    title: 'UI/UX Web3 Designer',
    company: 'Layer2 Labs',
    location: 'Remote',
    posted: '1 day ago',
    tags: ['Figma', 'Design System', 'Web3'],
    budget: '3,500 USDC',
    type: 'contract',
    cta: 'Apply Now',
    status: 'Litige',
    expected: 'Maquettes completes du dashboard, handoff Figma + specs responsive.',
    delivered: 'Premieres maquettes livre, sections manquantes selon client.',
    applied: false,
    applicants: [
      {
        id: 'app-6',
        name: 'Noah Kim',
        title: 'Product Designer',
        rate: '85 USDC/hr',
        availability: '15 hrs/week',
        skills: ['Figma', 'Design System', 'Prototype'],
        note: 'A livré des dashboards DeFi responsives.',
      },
      {
        id: 'app-7',
        name: 'Emma Clark',
        title: 'UX/UI Designer',
        rate: '90 USDC/hr',
        availability: '18 hrs/week',
        skills: ['UX research', 'Motion', 'Web3 onboarding'],
        note: 'Focus sur flows KYC/onboarding crypto.',
      },
    ],
  },
]

export const daoDisputes = [
  {
    id: 'dispute-1',
    name: 'Layer2 UI/UX Retainer',
    client: 'Layer2 Labs',
    amount: '12,000 USDC',
    period: 'Nov 1 - Dec 15',
    expected: 'Maquettes completes desktop et mobile, handoff Figma + spec responsive.',
    delivered: 'Maquettes livre a 70%, handoff incomplet sur mobile.',
    status: 'Litige',
    votesFor: 62,
    totalVoters: 100,
  },
  {
    id: 'dispute-2',
    name: 'Smart Contract Audit',
    client: 'BlockChain Inc',
    amount: '240,000 USDC',
    period: 'Dec 15 - Dec 30',
    expected: 'Audit complet + rapport final + recommandations de mitigation.',
    delivered: 'Audit partiel, rapport intermediaire fourni.',
    status: 'Litige',
    votesFor: 48,
    totalVoters: 100,
  },
]

export const messagesData = {
  conversations: [
    { name: 'CryptoVentures LLC', lastMessage: 'Last message 10:35 AM' },
    { name: 'Digital Arts Co', lastMessage: 'Last message 9:20 AM' },
    { name: 'BlockChain Inc', lastMessage: 'Last message 8:05 AM' },
  ],
  threads: {
    'CryptoVentures LLC': [
      { id: 1, from: 'client', author: 'CryptoVentures LLC', text: "Hi! How's the project going?", time: '10:30 AM' },
      { id: 2, from: 'me', author: 'You', text: "Great! I'm finishing the final touches on the UI.", time: '10:32 AM' },
      { id: 3, from: 'client', author: 'CryptoVentures LLC', text: 'Perfect! When can we expect delivery?', time: '10:33 AM' },
      { id: 4, from: 'me', author: 'You', text: 'Should be ready by Friday as planned.', time: '10:35 AM' },
    ],
    'Digital Arts Co': [
      { id: 5, from: 'client', author: 'Digital Arts Co', text: 'Can you share the latest NFT drop preview?', time: '9:12 AM' },
      { id: 6, from: 'me', author: 'You', text: 'Uploading now, will ping when done.', time: '9:14 AM' },
      { id: 7, from: 'client', author: 'Digital Arts Co', text: 'Thanks! Make sure mobile is covered.', time: '9:20 AM' },
    ],
    'BlockChain Inc': [
      { id: 8, from: 'client', author: 'BlockChain Inc', text: 'Reminder: audit call at 2 PM UTC.', time: '8:00 AM' },
      { id: 9, from: 'me', author: 'You', text: 'Confirmed. I will bring the coverage report.', time: '8:05 AM' },
    ],
  },
}

export const profileData = {
  name: 'Jordan Doe',
  title: 'Senior Web3 Engineer',
  location: 'Remote - Worldwide',
  rate: '120 USDC/hr',
  availability: '10-15 hrs/week',
  bio: 'Building secure, performant Web3 products: DeFi, NFT, and smart contract platforms.',
  skills: ['Solidity', 'TypeScript', 'React', 'Next.js', 'Hardhat', 'Ethers.js', 'Rust (basic)'],
  highlights: [
    'Audited $250M TVL protocols (no criticals post-release)',
    'Shipped NFT marketplace reaching 150k users',
    'Deployed L2 payment rails reducing fees by 38%',
  ],
  portfolio: [
    { label: 'DeFi Dashboard', link: '#', tech: 'React, Ethers.js' },
    { label: 'NFT Marketplace', link: '#', tech: 'Next.js, Solidity' },
    { label: 'Audit Reports', link: '#', tech: 'Hardhat, Slither' },
  ],
}
